POST http://localhost:3003/api/blogs/6373e04c84e3d3087476feaf/comments
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYzMzllYTIyNDRmYWUyMDEzNDE3ODY5ZiIsImlhdCI6MTY2ODUzODk2OH0.ag6KSMt-3OtXimbAgD151MP_jhE7U4VozHUgTDzBZHc

{
    comment: "test"
}